name:    curator
version: 2.0.0.0

ghc-options:
- -optP-Wno-nonportable-include-path # workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)

dependencies:
- base >=4.10 && < 5
- http-client
- http-client-tls
- pantry
- path
- path-io
- rio
- rio-prettyprint
- yaml

library:
  source-dirs: src
  exposed-modules:
  - Curator
  dependencies:
  - Cabal
  - bytestring
  - conduit
  - tar

executables:
  curator:
    ghc-options: -threaded
    source-dirs: app
    main: curator.hs
    dependencies:
    - curator
    - http-download
    - optparse-simple
  casa-curator:
    ghc-options: -threaded
    main: casa-curator.hs
    source-dirs: app
    dependencies:
      - curator
      - casa-client
      - conduit
      - persistent
      - rio-orphans
      - lens
      - resourcet
      - optparse-applicative
      - text
      - optparse-simple
      - containers
      - aeson
      - http-conduit
      - syb
      - persistent-sqlite
      - persistent-template
      - time
      - monad-logger
