name:    curator
version: 2.0.0.0

ghc-options:
- -optP-Wno-nonportable-include-path # workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)

dependencies:
- base >=4.10 && < 5
- http-client
- http-client-tls
- pantry
- path
- path-io
- rio
- rio-prettyprint
- yaml

library:
  source-dirs: src
  exposed-modules:
  - Curator
  dependencies:
  - Cabal
  - amazonka
  - amazonka-s3
  - blaze-html
  - bytestring
  - conduit
  - conduit-extra
  - cryptonite
  - cryptonite-conduit
  - html-conduit
  - memory
  - mime-types
  - mtl
  - resourcet
  - tar
  - xml-conduit
  - xml-types

executables:
  curator:
    source-dirs: app
    main: Main.hs
    dependencies:
    - curator
    - http-download
    - optparse-simple
  casa-curator:
    main: casa-curator.hs
    source-dirs: app
    dependencies:
      - curator
      - casa-client
      - conduit
      - persistent
      - rio-orphans
      - lens
      - resourcet
      - optparse-applicative
      - text
      - optparse-simple
      - containers
