resolver: lts-13.28
packages:
- .

# For local dev
# - ../pantry
# - ../casa/casa-client
# - ../casa/casa-types

extra-deps:
- http-download-0.1.0.0
- rio-prettyprint-0.1.0.0
- ansi-terminal-0.9.1
- rio-0.1.10.0

#- pantry-0.1.1.0
- github: commercialhaskell/pantry
  commit: 3cddc2bb799bf475979b0743f56623ea3b8732a1

- github: fpco/casa
  commit: 8ff6b5fd6b4136f8104628d61ca81e7b64c8c553
  subdirs:
     - casa-client
     - casa-types
